### ISSUE TITLE
barrierc cannot be properly shut down

### ISSUE THREAD

**Issue by yan12125** [input-leap/input-leap#1454]
### What happened?

When I shut down barrierc using "Stop" from barrier GUI, barrierc is not actually shut down, and after 5 seconds, barrier kills barrierc with SIGKILL.

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

420de96f3d280089ee929804bf8cecc35de0c28b

### If applicable, where did you install Barrier from?

From the AUR package maintained by me https://aur.archlinux.org/packages/input-leap-git

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows

### What OS versions are you using?

Server: Arch Linux latest
Client: Windows 10 21H2

### Relevant log output

```shell
$ sudo gdb
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) attach 367525
Attaching to process 367525
[New LWP 367526]
[New LWP 367527]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f7e44aaca55 in clock_nanosleep@GLIBC_2.2.5 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f7e44aaca55 in clock_nanosleep@GLIBC_2.2.5 () from /usr/lib/libc.so.6
#1  0x00007f7e44ab1717 in nanosleep () from /usr/lib/libc.so.6
#2  0x000055eb2c42b65e in ArchSleepUnix::sleep (this=<optimized out>, timeout=0.050000000000000003) at /usr/src/debug/input-leap/src/lib/arch/unix/ArchSleepUnix.cpp:74
#3  0x000055eb2c42a01b in ArchMultithreadPosix::wait (this=0x7ffe7cc36b48, target=0x55eb2e17ad90, timeout=-1)
    at /usr/src/debug/input-leap/src/lib/arch/unix/ArchMultithreadPosix.cpp:329
#4  0x000055eb2c47af97 in Thread::wait (timeout=-1, this=<optimized out>) at /usr/src/debug/input-leap/src/lib/mt/Thread.cpp:107
#5  SocketMultiplexer::~SocketMultiplexer (this=<optimized out>, this=<optimized out>) at /usr/src/debug/input-leap/src/lib/net/SocketMultiplexer.cpp:64
#6  0x000055eb2c4363ce in std::default_delete<SocketMultiplexer>::operator() (this=<optimized out>, __ptr=0x55eb2e17cc60) at /usr/include/c++/11.2.0/bits/unique_ptr.h:79
#7  std::default_delete<SocketMultiplexer>::operator() (__ptr=0x55eb2e17cc60, this=<optimized out>) at /usr/include/c++/11.2.0/bits/unique_ptr.h:79
#8  std::unique_ptr<SocketMultiplexer, std::default_delete<SocketMultiplexer> >::~unique_ptr (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/11.2.0/bits/unique_ptr.h:361
#9  App::~App (this=<optimized out>, this=<optimized out>) at /usr/src/debug/input-leap/src/lib/inputleap/App.cpp:76
#10 0x000055eb2c426a42 in main (argc=12, argv=<optimized out>) at /usr/src/debug/input-leap/src/cmd/barriers/barriers.cpp:63
(gdb) info threads
  Id   Target Id                                     Frame
* 1    Thread 0x7f7e44899100 (LWP 367525) "barriers" 0x00007f7e44aaca55 in clock_nanosleep@GLIBC_2.2.5 () from /usr/lib/libc.so.6
  2    Thread 0x7f7e44895640 (LWP 367526) "barriers" 0x00007f7e44a1724a in sigtimedwait () from /usr/lib/libc.so.6
  3    Thread 0x7f7e44094640 (LWP 367527) "barriers" 0x00007f7e44a5e15a in __futex_abstimed_wait_common () from /usr/lib/libc.so.6
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f7e44895640 (LWP 367526))]
#0  0x00007f7e44a1724a in sigtimedwait () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f7e44a1724a in sigtimedwait () from /usr/lib/libc.so.6
#1  0x00007f7e44a168ec in sigwait () from /usr/lib/libc.so.6
#2  0x000055eb2c42a1b4 in ArchMultithreadPosix::threadSignalHandler () at /usr/src/debug/input-leap/src/lib/arch/unix/ArchMultithreadPosix.cpp:588
#3  0x00007f7e44a615c2 in start_thread () from /usr/lib/libc.so.6
#4  0x00007f7e44ae6584 in clone () from /usr/lib/libc.so.6
(gdb) thread 3
[Switching to thread 3 (Thread 0x7f7e44094640 (LWP 367527))]
#0  0x00007f7e44a5e15a in __futex_abstimed_wait_common () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f7e44a5e15a in __futex_abstimed_wait_common () from /usr/lib/libc.so.6
#1  0x00007f7e44a60960 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libc.so.6
#2  0x00007f7e44cc7c51 in __gthread_cond_wait (__mutex=<optimized out>, __cond=0x55eb2e17cc98)
    at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:865
#3  std::__condvar::wait (__m=..., this=0x55eb2e17cc98) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/std_mutex.h:155
#4  std::condition_variable::wait (this=this@entry=0x55eb2e17cc98, __lock=...) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/condition_variable.cc:41
#5  0x000055eb2c47a8c4 in std::condition_variable::wait<SocketMultiplexer::service_thread()::<lambda()> > (__p=..., __lock=..., this=0x55eb2e17cc98)
    at /usr/include/c++/11.2.0/condition_variable:103
#6  SocketMultiplexer::service_thread (this=0x55eb2e17cc60) at /usr/src/debug/input-leap/src/lib/net/SocketMultiplexer.cpp:144
#7  operator() (__closure=<optimized out>) at /usr/src/debug/input-leap/src/lib/net/SocketMultiplexer.cpp:57
#8  std::__invoke_impl<void, SocketMultiplexer::SocketMultiplexer()::<lambda()>&> (__f=...) at /usr/include/c++/11.2.0/bits/invoke.h:61
#9  std::__invoke_r<void, SocketMultiplexer::SocketMultiplexer()::<lambda()>&> (__fn=...) at /usr/include/c++/11.2.0/bits/invoke.h:154
#10 std::_Function_handler<void(), SocketMultiplexer::SocketMultiplexer()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/11.2.0/bits/std_function.h:291
#11 0x000055eb2c47e722 in std::function<void ()>::operator()() const (this=0x55eb2e17b2c0) at /usr/include/c++/11.2.0/bits/std_function.h:560
#12 Thread::threadFunc(std::function<void ()> const&) (func=...) at /usr/src/debug/input-leap/src/lib/mt/Thread.cpp:141
#13 operator() (__closure=0x55eb2e17b2c0) at /usr/src/debug/input-leap/src/lib/mt/Thread.cpp:33
#14 std::__invoke_impl<void, Thread::Thread(const std::function<void()>&)::<lambda()>&> (__f=...) at /usr/include/c++/11.2.0/bits/invoke.h:61
#15 std::__invoke_r<void, Thread::Thread(const std::function<void()>&)::<lambda()>&> (__fn=...) at /usr/include/c++/11.2.0/bits/invoke.h:154
#16 std::_Function_handler<void(), Thread::Thread(const std::function<void()>&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/11.2.0/bits/std_function.h:291
#17 0x000055eb2c42a4e8 in std::function<void ()>::operator()() const (this=0x55eb2e17ada0) at /usr/include/c++/11.2.0/bits/std_function.h:560
#18 ArchMultithreadPosix::doThreadFunc (thread=0x55eb2e17ad90, this=0x7ffe7cc36b48) at /usr/src/debug/input-leap/src/lib/arch/unix/ArchMultithreadPosix.cpp:531
#19 ArchMultithreadPosix::threadFunc (vrep=0x55eb2e17ad90) at /usr/src/debug/input-leap/src/lib/arch/unix/ArchMultithreadPosix.cpp:513
#20 0x00007f7e44a615c2 in start_thread () from /usr/lib/libc.so.6
#21 0x00007f7e44ae6584 in clone () from /usr/lib/libc.so.6
(gdb) c
Continuing.
[Thread 0x7f7e44094640 (LWP 367527) exited]
[Thread 0x7f7e44895640 (LWP 367526) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb)
The program is not being run.
quit)
```

### Any other information

Logs above are for barrierc after I hit "Stop" and before SIGKILL happens. Looks like a thread is waiting for new events and never terminates.

By the way, a similar issues happens when I tried to shut down barrierd on Windows with `net stop barrierd`. I built Windows binaries using MinGW with many patches, so that might not be an upstream issue.

**Comment by whot** [comment]
Should be fixed by #1494

**Comment by yan12125** [comment]
Thanks! The issue is gone for commit 1b5aae98e73c840c4108cb1de3d09e3ad620383a on Arch Linux. I will find time to build the latest commit for Windows.

**Comment by shymega** [comment]
Closing as fixed.
